Update to remove setup as it's already done in our environment

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -15,19 +15,22 @@ inputs:
 runs:
   using: composite
   steps:
-    - run: |
-        export INPUT_GITHUB_TOKEN=${{ inputs.github_token }};
-        FILEPATH="${{ github.action_path }}/setup.sh"
-        if [ -f "$FILEPATH" ]; then
-          chmod +x $FILEPATH
-          $FILEPATH
-        fi
-      shell: bash
+#    - run: |
+#        export INPUT_GITHUB_TOKEN=${{ inputs.github_token }};
+#        FILEPATH="${{ github.action_path }}/setup.sh"
+#        if [ -f "$FILEPATH" ]; then
+#          chmod +x $FILEPATH
+#          $FILEPATH
+#        fi
+#      shell: bash
     - run: |
         export INPUT_GITHUB_TOKEN=${{ inputs.github_token }};
         FILEPATH="${{ github.action_path }}/entrypoint.sh"
         if [ -f "$FILEPATH" ]; then
           chmod +x $FILEPATH
           $FILEPATH
+        else
+          # Exit as not found ( in bash exit code )
+          exit 127
         fi
       shell: bash
